plugins {
    id 'application'
    id 'java'
}

repositories {
    mavenCentral()
}

def javafxVersion = '21.0.2'
def osName = System.getProperty('os.name').toLowerCase()

def javafxPlatform
if (osName.contains('win')) {
    javafxPlatform = 'win'
} else if (osName.contains('mac')) {
    javafxPlatform = 'mac'
} else {
    javafxPlatform = 'linux'
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'

    implementation "org.openjfx:javafx-base:${javafxVersion}:${javafxPlatform}"
    implementation "org.openjfx:javafx-graphics:${javafxVersion}:${javafxPlatform}"
    implementation "org.openjfx:javafx-controls:${javafxVersion}:${javafxPlatform}"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'cli.Main'
}

test {
    useJUnitPlatform()
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

run {
    jvmArgs = [
            '-Dfile.encoding=UTF-8',
            '-Dconsole.encoding=UTF-8',
            '-Dstdout.encoding=UTF-8'
    ]
    standardInput = System.in
}

tasks.register('runUi', JavaExec) {
    group = 'application'
    description = 'Runs JavaFX UI'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'ui.UiLauncher'
    jvmArgs = ['-Dfile.encoding=UTF-8']
}
